### ISSUE TITLE
Better CONTRIBUTING.md

### ISSUE THREAD

**Issue by rishabh-live** [forum2k-smit/DSA-OPEN-SOURCE#14]
### Write a better CONTRIBUTING.md file for this repository

- [x] Assigned
- [x] Pull Request
- [x] Accepted

**Comment by LuizHAP** [comment]
I will create this!

**Comment by HarshitAditya27** [comment]
Hi, I would like to work on this issue, Can I change some parts of CONTRIBUTING.md and make it better?  Can you assign me this issue?

**Comment by rishabh-live** [comment]
@HarshitAditya27 Kindly register here: https://forms.office.com/r/9Zywhm2S7X with your college registration number, if you are a student of SMIT. If Not You can ignore this. This Repo is strictly for students of SMIT.

**Comment by HarshitAditya27** [comment]
Hello, @rishabh-live I have submitted the form 👍.

**Comment by rishabh-live** [comment]
@HarshitAditya27 You have been assigned the task.

**Comment by HarshitAditya27** [comment]
Thanks a lot, @rishabh-live for assigning me this issue. Now I will start working on the issue and I will update you about the issue here.

**Comment by HarshitAditya27** [comment]
@rishabh-live Can I add some screenshots, gif, and some emojis in the MD file?

**Comment by rishabh-live** [comment]
> @rishabh-live Can I add some screenshots, gif, and some emojis in the MD file?

No Giphys allowed as it is official Repository of Department. Although you can add emojis.

**Comment by HarshitAditya27** [comment]
@rishabh-live I have updated contributing.MD file. Should I send you the screenshot of the updated MD file here so that if you want some changes I will do it or should I create a pull request?

**Comment by rishabh-live** [comment]
@HarshitAditya27 create a pull request, I will write if I want some changes.

**Comment by HarshitAditya27** [comment]
Ok 👍
