### ISSUE TITLE
Binary Trees

### ISSUE THREAD

**Issue by rishabh-live** [forum2k-smit/DSA-OPEN-SOURCE#38]
lang: python ( @rishabh99-rc )
- [x] Assigned
- [ ] Pull Request
- [ ] Accepted

**Comment by RahulPalve** [comment]
Done @rishabh-live

**Comment by rishabh-live** [comment]
Are you a student at SMIT? if yes fill this form up https://forms.office.com/r/9Zywhm2S7X

**Comment by RahulPalve** [comment]
@rishabh-live  Hacktoberfest is foss event right, Do i need to be student to contribute. Its against hacktoberfests ethics

**Comment by rishabh-live** [comment]
> @rishabh-live Hacktoberfest is foss event right, Do i need to be student to contribute. Its against hacktoberfests ethics


This is for students of SMIT so that they learn Open Source Contributions. Its major focus is on learning. Additionally, It is not against ethics because it is a repository Code Of Conduct.

**Comment by vivaan19** [comment]
> @rishabh-live Hacktoberfest is foss event right, Do i need to be student to contribute. Its against hacktoberfests ethics

It is not as because

**Comment by rishabh99-rc** [comment]
@rishabh-live can you assign this to me. 

I have already pushed my work for the Merge Sort Algo.
