### ISSUE TITLE
Program to implement Linear search Algorithm

### ISSUE THREAD

**Issue by rishabh-live** [forum2k-smit/DSA-OPEN-SOURCE#6]
- [x] Assigned
- [x] Pull Request
- [ ] Accepted

**Comment by Saurav-Sutaria** [comment]
@rishabh-live I am interested in this issue, please assign this to me.

**Comment by rishabh-live** [comment]
> @rishabh-live I am interested in this issue, please assign this to me.

This repository is strictly for SMIT students. 
Fill this form and comment for the assignment: https://forms.office.com/r/9Zywhm2S7X

**Comment by Saurav-Sutaria** [comment]
ok no problem, I am not a SMIT student. :(

**Comment by jayantaadhikary** [comment]
Can this be assigned to me? I filled the form and would like to use python/javascript to do this.

**Comment by rishabh-live** [comment]
Ok I have verified your entry. Can you do it in both languages?
Python as well as JS.

**Comment by jayantaadhikary** [comment]
> Ok I have verified your entry. Can you do it in both languages? Python as well as JS.

Yeah sure, I can do it for both.  Can I make two pull requests then? 1 for Python and 1 for JS, so that I can get 2 entries?

**Comment by rishabh-live** [comment]
> > Ok I have verified your entry. Can you do it in both languages? Python as well as JS.
> 
> Yeah sure, I can do it for both. Can I make two pull requests then? 1 for Python and 1 for JS, so that I can get 2 entries?

@jayantaadhikary definitely you can.
