### ISSUE TITLE
 Implement a Binary search Algorithm without recursion

### ISSUE THREAD

**Issue by rishabh-live** [forum2k-smit/DSA-OPEN-SOURCE#7]
- [x] Assigned
- [x] Pull Request
- [x] Accepted

**Comment by tamalCodes** [comment]
Can i be assigned this issue ?

**Comment by rishabh-live** [comment]
> Can i be assigned this issue ?

Sorry, This repository is only available to students of Sikkim Manipal Institute of Technology.

**Comment by DevGautam2000** [comment]
I would want to do this

**Comment by DevGautam2000** [comment]
I have registered using the form

**Comment by rishabh-live** [comment]
@DevGautam2000 You will only be aloted on task at a time.

**Comment by Amisha-Agrawal** [comment]
Can i be assigned this issue ?

**Comment by rishabh-live** [comment]
@Amisha-Agrawal ok sure
